USE APUBSPLDB;

-- Start: Create Logins --
CREATE LOGIN [PeterCarter]		WITH PASSWORD='ifT3n7a1Z1INQj6rPqyJxmdvXtqomm8M', DEFAULT_DATABASE=APUBSPLDB;
CREATE LOGIN [RajRaj]		WITH PASSWORD='2j1S3M8OMwS9RKzAy5oig1rEAEx29BuK', DEFAULT_DATABASE=APUBSPLDB;
CREATE LOGIN [AdamMuhammad] 	WITH PASSWORD='oke4FufIT2wY09A1Ttn2Dozh8wZeTF24', DEFAULT_DATABASE=APUBSPLDB;
CREATE LOGIN [IanStirk]		WITH PASSWORD='cmYJZGky5M536cN031U55gSpDZ2OHZQP', DEFAULT_DATABASE=APUBSPLDB;
CREATE LOGIN [DaudSalim]		WITH PASSWORD='fX4kcpnec14HjnaIHp61t89k7ZFfxo0v', DEFAULT_DATABASE=APUBSPLDB;
-- End: Create Logins --

-- Start: Enable Logins
ALTER LOGIN [PeterCarter]		ENABLE;
ALTER LOGIN [RajRaj]			ENABLE;
ALTER LOGIN [AdamMuhammad] 		ENABLE;
ALTER LOGIN [IanStirk]		ENABLE;
ALTER LOGIN [DaudSalim]		ENABLE;
-- End: Enable Logins

-- Start: Create Users --
CREATE USER [PeterCarter]		FOR LOGIN [PeterCarter];
CREATE USER [RajRaj]			FOR LOGIN [RajRaj];
CREATE USER [AdamMuhammad]		FOR LOGIN [AdamMuhammad];
CREATE USER [IanStirk]		FOR LOGIN [IanStirk];
CREATE USER [DaudSalim]		FOR LOGIN [DaudSalim];
-- End: Create Users --


